### ISSUE TITLE
Add button to hide nodes not in `nodeSettings`

### ISSUE THREAD

**Issue by joesobo** [joesobo/CodeGraphy#42]
It would be nice to have a button that could hide any files that are `not` directly included into this list

```json
"codegraphy.nodeSettings": [
    {
      "extension": ".js",
      "color": "#4985be"
    },
    {
      "extension": ".ts",
      "color": "#eac73e"
    },
    {
      "extension": ".vue",
      "color": "#74cc4b"
    },
    {
      "extension": ".json",
      "color": "#dc6844"
    }
  ],
```

The button should function and look similar to the `hover` or `hide labels` option and be beneath them in the UI

**Comment by gVirtu** [comment]
Can I attempt this one? :)

Also, what name shall we give this button?

Thanks!

**Comment by joesobo** [comment]
@gVirtu Absolutely thanks for reaching out!

As for the name I dont have a strong opinion right now. Perhaps `Hide Unused Files` or `Selected Files Only`? I'm open to suggestions

Also please reach out if there's anything I can help out with, thanks! :)

**Comment by gVirtu** [comment]
@joesobo sure! Might go with `Hide Unused Nodes` to along with `Hide Labels` nicely. :)

I'm having some trouble setting up though, graphs aren't showing up. I'm using CodeGraphy's own codebase to test and it also happens when using the prebuilt extension installed from VSCode.

After some debugging I found that `fetchDirFiles` was throwing an exception (ENOENT) when trying to read `dirContent`. This might be because I'm in a unix environment and `vscode.workspace.workspaceFolders[0].uri.path` looked like `"/home/{username}/.../CodeGraphy"`, so the first slash gets stripped out by `substring(1)` and the resulting path looks like a relative one.

I'm not too familiar with the vscode APIs, is there a clean way around this?

Thanks!

**Comment by gVirtu** [comment]
Fantastic, thanks! Will test it out later today. 

Also thank you for the settings sample, this will definitely speed things up a ton. :)
